config:
  azure-native:location: WestUS
  request-a-dasher:developerId: 14e84291-d900-4c20-8528-ed6ca8de660f
  request-a-dasher:googleApiKey:
    secure: AAABAGA3V+q/HTYpQ2cva8GIovhcVRod+6+6QiMN0gin+hJgffmHo+7RC0yk1DPJSVFnY/6BJxBYZUU7Gqutr9JYkLpEKgo=
  request-a-dasher:googleProviderAuthenticationClientId: 879682729138-b6pvks3oh0qid7it8v3llkf29f9ek86r.apps.googleusercontent.com
  request-a-dasher:googleProviderAuthenticationSecret:
    secure: AAABAHdBFs5Y0jkLoZ7PFbSY4MEZ6G9tnjMAKZ0LePSlbcwTRJPo/WC2iaAcuuN68BqTB0s0yVBM4eS0UqNiydoxww==
  request-a-dasher:keyId: 4635a05d-f7f5-42f2-aa6a-41e0ff6b3447
  request-a-dasher:signingSecret:
    secure: AAABAG3sngWsm2eJIfYFmR3UXl0EPjaqhh/7rKBoRN9IPOPVAZxvzAlAzxJnoATe+9O44rQU/U6vyvjM5g/I9qxnJ9rW/rPy+sGA
